first commit

diff --git a/.github/workflows/deploy-docker.yml b/.github/workflows/deploy-docker.yml
--- a/.github/workflows/deploy-docker.yml
+++ b/.github/workflows/deploy-docker.yml
@@ -22,6 +22,22 @@ jobs:
           go-version: 1.22.11
         id: go
 
+      - name: Check Secret Availability
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "❌ DOCKERHUB_USERNAME is missing!"
+            exit 1
+          else
+            echo "✅ DOCKERHUB_USERNAME is set!"
+          fi
+
+          if [ -z "${{ secrets.DOCKERHUB_PASSWORD }}" ]; then
+            echo "❌ DOCKERHUB_PASSWORD is missing!"
+            exit 1
+          else
+            echo "✅ DOCKERHUB_PASSWORD is set!"
+          fi
+
       - name: Get dependencies
         run: |
           go mod download
@@ -34,7 +50,7 @@ jobs:
         uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
       - name: Extract metadata (tags, labels) for Docker
         id: meta
